on:
  - workflow_dispatch

jobs:
  test-cfn-lint:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint -t ./**/*.yaml
